[package]
name = "ethabi-derive"
version = "5.1.1"
authors = ["Parity Technologies <admin@parity.io>"]
homepage = "https://github.com/paritytech/ethabi"
license = "MIT"
keywords = ["ethereum", "eth", "abi", "solidity", "derive"]
description = "Easy to use conversion of ethereum contract calls to bytecode."

[lib]
proc-macro = true

[dependencies]
ethabi = { path = "../ethabi", version = "5.0" }
heck = "0.3"
syn = "0.13"
quote = "0.5.1"
