[package]
name = "ethabi-cli"
version = "8.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
keywords = ["ethereum", "eth", "abi", "solidity", "cli"]
description = "Easy to use cli for conversion of ethereum contract calls to bytecode."
homepage = "https://github.com/paritytech/ethabi"
license = "MIT/Apache-2.0"

[dependencies]
rustc-hex = "2.0"
serde = "1.0"
serde_derive = "1.0"
docopt = "1.0"
ethabi = { version = "8.0.0", path = "../ethabi" }
error-chain = { version = "0.12.1", default-features = false }
tiny-keccak = "1.0"

[features]
backtrace = ["error-chain/backtrace"]

[[bin]]
name = "ethabi"
path = "src/main.rs"
